### ISSUE TITLE
incompatibility between pandas and numpy in 1.2.1

### ISSUE THREAD

**Issue by nimzodisaster** [clementpoiret/HSF#37]
**Describe the bug**
seems like there is an incompatibility between pandas and numpy

(HSF) jlee38@mothership:/mnt/colony/ds/HSF$ hsf -h
Traceback (most recent call last):
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/bin/hsf", line 5, in <module>
    from hsf.factory import start
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/hsf/factory.py", line 5, in <module>
    import ants
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/ants/__init__.py", line 4, in <module>
    from .core import *
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/ants/core/__init__.py", line 1, in <module>
    from .ants_image_io import (image_header_info,
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/ants/core/ants_image_io.py", line 24, in <module>
    from ants.decorators import image_method
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/ants/decorators.py", line 2, in <module>
    from ants.core.ants_image import ANTsImage
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/ants/core/ants_image.py", line 17, in <module>
    import pandas as pd
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/mnt/colony/pythonENVS/anaconda3/envs/HSF/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Debian]
 - Python: [e.g. 3.9.1]
 - HSF Version: [e.g. 0.1.1]
 - Relevant settings: [e.g. segmentation=bagging_fast]

**Additional context**

**Comment by nimzodisaster** [comment]
It seems that antspyx==0.5.4 is not compatible with ROILoc; downgraded antspyx to 0.4.2 and it started running.

**Comment by clementpoiret** [comment]
Thanks for your issue. I'll update roiloc asap :+1:

**Comment by clementpoiret** [comment]
Should be solved by v1.2.2 👌
